### ISSUE TITLE
Pretrained model of DeblurNet

### ISSUE THREAD

**Issue by oaishi** [sczhou/DAVANet#13]
Dear Shangchen Zhou,
for my research scope, I needed to infer the results produced by the single DeblurNet. I followed the procedure described ([here](https://github.com/sczhou/DAVANet/issues/1#issuecomment-490501385)) and was able to switch to do the Single Deblurnet configuration. I shall be grateful if you kindly help me to get the checkpoint of the single deblurnet. Specifically, I am looking for the pre-trained model which is referred as "**Ours-Single**" in table 1 of the paper.

![codebert](https://user-images.githubusercontent.com/22328326/90290422-ac4b3e00-de9f-11ea-982f-a2687dcf98c3.PNG)

Thanking you,
Oaishi.

**Comment by sczhou** [comment]
Hi Oaishi,

I am so sorry that the Single Deblurnet model can not be found since I have left the previous company last year and I didn't keep a local copy for myself. However, it should be easy to reproduce the training process of Single Deblurnet by slightly modifying the training code. I would be glad to answer the questions if you would like to reproduce the training by yourself.
